version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: tasksbot-postgres-1
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: postgres
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U postgres"]
      interval: 10s
      timeout: 3s
      retries: 10
    volumes:
      - pgdata:/var/lib/postgresql/data
    # ВНЕШНИЙ порт НЕ публикуем, внутри сети контейнеров бд доступна по хосту "postgres:5432"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file: .env
    depends_on:
      postgres:
        condition: service_healthy
    command: python tasks_bot.py
    # Для разработки можно подмонтировать код, чтобы не пересобирать образ:
    # volumes:
    #   - ./:/app

volumes:
  pgdata:
